version: '3.4'

services:
    ticketpusherapi:
        image: ${DOCKER_REGISTRY}ticketpusherapi
        build:
            context: .
            dockerfile: api.dockerfile

    ticketpusherweb:
        image: ${DOCKER_REGISTRY}ticketpusherweb
        build:
            context: .
            dockerfile: web.dockerfile
        depends_on:
            - "ticketpusherapi"
        ports:
            - "80:80"
